esphome:
  name: intellisense-build
  libraries:
    - xxtea-iot-crypt@2.0.1

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: "dummy"
  password: "dummypassword"

external_components:
  - source: components

ble_client:
  - mac_address: 00:04:2f:00:00:00
    id: dummy_eco2

climate:
  - platform: danfoss_eco
    name: "Dummy eTRV"
    ble_client_id: dummy_eco2
    pin_code: "0000"
    secret_key: deadbeefcafebabedeadbeefcafebabe
    battery_level:
      name: "Dummy Battery"
    temperature:
      name: "Dummy Temperature"
    problems:
      name: "Dummy Problems"
    update_interval: 30min
